services:

  tmp_api:
    build:
      context: .
      dockerfile: Dockerfile
    image: tpmacard-api
    container_name: tpmacard--backend
    volumes:
      - .:/app
    ports:
      - '8080:8000'
    env_file:
      - ./.env
    restart: unless-stopped
